# Generated by Django 5.1 on 2024-08-23 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_wishlist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='user_id',
            field=models.BigIntegerField(db_index=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(db_index=True, max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='wishlist',
            name='user_id',
            field=models.BigIntegerField(db_index=True),
        ),
    ]
